### ISSUE TITLE
Error C2-11828-1 After opening Youtube on the PS5

### ISSUE THREAD

**Issue by M0chaCat** [ywnico/vitaki-fork#10] opened 2024-10-26 23:24 UTC
**Describe the bug**
Once YouTube is running on the PS5 you are unable to remote into it, and it will crash with error C2-11828-1

**Debug Log**
Couldn't Find

**To Reproduce**
1. Connect to PS5
2. Open YouTube
3. Vita app crashes with error C2-11828-1

**Expected behavior**
It runs fine(?)

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: PSVITA
 - Version 0.05
 - Device Vita

**Additional context**
NA

**Comment by ywnico** [comment] 2024-10-27 04:15
Interesting, I tested and confirmed that opening YouTube crashes for me too.

When YouTube first opens, a message appears that says screen recording will be disabled; I wonder if this is related.

**Comment by ywnico** [comment] 2024-10-27 04:24
I don't have a PS4 to test with, but apparently this is an issue with the regular remote play app as well (https://old.reddit.com/r/PS4/comments/fip4d3/remote_play_wont_youtube_but_browser_will/, https://old.reddit.com/r/playstation/comments/sz7ikf/i_forgot_that_youtube_doesnt_work_on_remote_play/) and with the PS portal (https://old.reddit.com/r/PlaystationPortal/comments/18khlfb/can_i_watch_content_on_the_ps_portal/). Seems to apply to Netflix as well.

So, I think this is a "feature" due to the DRM (in order to...somehow prevent piracy or something) and cannot be fixed on our end.... Pretty disappointing, since it would be a good solution for watching Youtube and Netflix.

**Comment by ywnico** [comment] 2024-10-27 04:25
I'm going to close this issue since I believe it is not possible to fix :(

But, thank you for opening the issue, @M0chaCat.

**Closed as completed by ywnico** 2024-10-27 04:25 UTC
